print("M             M                 C")
print("M  M        M M               C")
print("M   M    M    M             C")
print("M      M      M            C")
print("M             M            C")
print("M             M            C")
print("M             M                C")
print("M             M                  C")
print("M             M                     C")